### ISSUE TITLE
Unknown NullPointerException in MasterServer

### ISSUE THREAD

**Issue by arves100** [GameProgressive/UniSpyServer#11]
Looks to be related when someone connects to the MasterServer under TCP (Particularry ServerBrowser)

Log:
```
[8/5/19 1:16:26 AM] [Error]    NOTICE: An Error occured at [MstrServer.AcceptClient] : System.NullReferenceException: Object reference not set to an instance of an object.
   at GameSpyLib.Network.TcpStream.ProcessReceive() in GameSpyLib/Network/TcpStream.cs:line 266
   at GameSpyLib.Network.TcpStream.BeginReceive() in GameSpyLib/Network/TcpStream.cs:line 159
   at RetroSpyServer.Servers.ServerBrowser.SBServer.ProcessAccept(TcpStream Stream) in RetroSpyServer/Servers/ServerBrowser/SBServer.cs:line 79

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at GameSpyLib.Network.TcpStream.ProcessReceive() in GameSpyLib/Network/TcpStream.cs:line 266
   at GameSpyLib.Network.TcpStream.IOComplete(Object sender, SocketAsyncEventArgs e) in GameSpyLib/Network/TcpStream.cs:line 454
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

```

**Comment by Sporesirius** [comment]
Fixed
